spring.application.name=chatbot-service
server.port=9990

spring.config.import=optional:configserver:http://localhost:9999

# CORRECT : seulement l'API key est requise
spring.ai.google.genai.api-key=AIzaSyBgelr5Qyr0PSq0UfVPtv1bWuBxw9WlmZ4
spring.ai.google.genai.model=gemini-1.5-flash

spring.ai.mcp.client.streamable-http.connections.mcprh.url=http://localhost:8989/mcp